name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir third-party
        git submodule add https://github.com/google/googletest third-party/gtest
        cd third-party/gtest && git checkout release-1.11.0 && cd ../..
        cmake -H. -B_build
        cmake --build _build
        ls _build
